/**
 * boaterslist-backend
 * REST api for boater&#39;s list suite of applications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: george@thearchitects.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 /**
 * (tsType: Categories, schemaOptions: { includeRelations: true })
 */
 export class Categories {
     'categoryId': number;
     'categoryNumber'?: string;
     'categoryName'?: string;
 
     static readonly discriminator: string | undefined = undefined;
 
     static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
         {
             "name": "categoryId",
             "baseName": "categoryId",
             "type": "number",
             "format": ""
         },
         {
             "name": "categoryNumber",
             "baseName": "categoryNumber",
             "type": "string",
             "format": ""
         },
         {
             "name": "categoryName",
             "baseName": "categoryName",
             "type": "string",
             "format": ""
         }    ];
 
     static getAttributeTypeMap() {
         return Categories.attributeTypeMap;
     }
     
     public constructor() {
     }
 }
 
 