/**
 * boaterslist-backend
 * REST api for boater&#39;s list suite of applications
 *
 * OpenAPI spec version: 1.1.0
 * Contact: george@thearchitects.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

 import { Locations } from './Locations';
 
 /**
 * (tsType: Companies, schemaOptions: { includeRelations: true })
 */
 export class Companies {
     'companyId': number;
     'companyName': string;
     'phoneNumber'?: string;
     'description'?: string;
     'address1'?: string;
     'address2'?: string;
     'city'?: string;
     'state'?: string;
     'zipCode'?: string;
     'contactPerson'?: string;
     'contactEmail'?: string;
     'bestFormOfCommunication'?: string;
     'website'?: string;
     'createdByUserId': number;
     'ownerAuthUserId'?: string;
     'dateCreated': Date;
     'locations'?: Array<Locations>;
 
     static readonly discriminator: string | undefined = undefined;
 
     static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
         {
             "name": "companyId",
             "baseName": "companyId",
             "type": "number",
             "format": ""
         },
         {
             "name": "companyName",
             "baseName": "companyName",
             "type": "string",
             "format": ""
         },
         {
             "name": "phoneNumber",
             "baseName": "phoneNumber",
             "type": "string",
             "format": ""
         },
         {
             "name": "description",
             "baseName": "description",
             "type": "string",
             "format": ""
         },
         {
             "name": "address1",
             "baseName": "address1",
             "type": "string",
             "format": ""
         },
         {
             "name": "address2",
             "baseName": "address2",
             "type": "string",
             "format": ""
         },
         {
             "name": "city",
             "baseName": "city",
             "type": "string",
             "format": ""
         },
         {
             "name": "state",
             "baseName": "state",
             "type": "string",
             "format": ""
         },
         {
             "name": "zipCode",
             "baseName": "zipCode",
             "type": "string",
             "format": ""
         },
         {
             "name": "contactPerson",
             "baseName": "contactPerson",
             "type": "string",
             "format": ""
         },
         {
             "name": "contactEmail",
             "baseName": "contactEmail",
             "type": "string",
             "format": ""
         },
         {
             "name": "bestFormOfCommunication",
             "baseName": "bestFormOfCommunication",
             "type": "string",
             "format": ""
         },
         {
             "name": "website",
             "baseName": "website",
             "type": "string",
             "format": ""
         },
         {
             "name": "createdByUserId",
             "baseName": "createdByUserId",
             "type": "number",
             "format": ""
         },
         {
             "name": "ownerAuthUserId",
             "baseName": "ownerAuthUserId",
             "type": "string",
             "format": ""
         },
         {
             "name": "dateCreated",
             "baseName": "dateCreated",
             "type": "Date",
             "format": "date-time"
         },
         {
             "name": "locations",
             "baseName": "locations",
             "type": "Array<LocationsWithRelations>",
             "format": ""
         }    ];
 
     static getAttributeTypeMap() {
         return Companies.attributeTypeMap;
     }
     
     public constructor() {
     }
 }
 
 