/**
 * boaterslist-backend
 * REST api for boater&#39;s list suite of applications
 *
 * OpenAPI spec version: 1.1.0
 * Contact: george@thearchitects.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Categories } from "./Categories";
 /**
 * (tsType: SubCategories, schemaOptions: { includeRelations: true })
 */
 export class SubCategories {
     'subCategoryId': number;
     'categoryId': number;
     'subCategoryNumber'?: string;
     'subCategoryName'?: string;
     'category'?: Categories;
 
     static readonly discriminator: string | undefined = undefined;
 
     static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
         {
             "name": "subCategoryId",
             "baseName": "subCategoryId",
             "type": "number",
             "format": ""
         },
         {
             "name": "categoryId",
             "baseName": "categoryId",
             "type": "number",
             "format": ""
         },
         {
             "name": "subCategoryNumber",
             "baseName": "subCategoryNumber",
             "type": "string",
             "format": ""
         },
         {
             "name": "subCategoryName",
             "baseName": "subCategoryName",
             "type": "string",
             "format": ""
         },
         {
             "name": "category",
             "baseName": "category",
             "type": "CategoriesWithRelations",
             "format": ""
         }    ];
 
     static getAttributeTypeMap() {
         return SubCategories.attributeTypeMap;
     }
     
     public constructor() {
     }
 }
 
 