version: "3.8"

services:
  init-db:
    environment:
      DB_HOST: ${BOATERSLIST_DB_HOST}
      DB_PORT: ${BOATERSLIST_DB_PORT}
      DB_USER: ${BOATERSLIST_DB_USER}
      DB_PASSWORD: ${BOATERSLIST_DB_PASSWORD}
    image: "mariadb:10.5.13"
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - .:/host
    working_dir: /host
    command: ./.cicd/init-db.sh
    depends_on:
      - db

  db:
    image: mariadb:10.5.13
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=${BOATERSLIST_DB_PASSWORD}"
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - "3306:3306"

  # TODO set password: https://opensearch.org/docs/latest/security-plugin/configuration/yaml/
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    restart: unless-stopped
    volumes:
      - ./opensearch-tmp.yml:/usr/share/opensearch/config/opensearch.yml
      - ./snapshots:/mnt/snapshots
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  # admin UI: http://localhost:8090
  db-admin:
    image: phpmyadmin:5.1.1
    restart: unless-stopped
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - "8090:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${BOATERSLIST_DB_HOST}
      - PMA_PORT=${BOATERSLIST_DB_PORT}
      - PMA_USER=${BOATERSLIST_DB_USER}
      - PMA_PASSWORD=${BOATERSLIST_DB_PASSWORD}

  # http://localhost:5601 (admin/admin)
  opensearch-admin:
    image: opensearchproject/opensearch-dashboards:1.2.0
    restart: unless-stopped
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://${BOATERSLIST_OPENSEARCH_HOST}"]'
      OPENSEARCH_USERNAME: "${BOATERSLIST_OPENSEARCH_USER}"
      OPENSEARCH_PASSWORD: "${BOATERSLIST_OPENSEARCH_PASSWORD}"

  sync:
    image: registry.gitlab.com/boaterslist/go-mysql-elasticsearch/go-mysql-elasticsearch:latest
    restart: unless-stopped
    volumes:
      - ./river.toml:/work/etc/river.toml
      - ./.cicd/river-hook.sh:/work/river-hook.sh
